21/moma_app/config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :works

end

21/moma_app/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  image       :text
#  created_at  :datetime
#  updated_at  :datetime
#  period      :string(255)
#

class Artist < ActiveRecord::Base
  has_many :works
end

21/moma_app/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  string     :string(255)
#  year       :string(255)
#  medium     :string(255)
#  style      :string(255)
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)
#  artist_id  :integer
#

class Work < ActiveRecord::Base
  belongs_to :artist
end

21/moma_app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def create
    artist = Artist.create(artist_params)
    redirect_to artist
  end

  def new
    @artist = Artist.new
  end

  def show
    @artist = Artist.find(params["id"])
  end

  def edit
    @artist = Artist.find(params['id'])
  end

  def destroy
    artist = Artist.find(params['id'])
    artist.destroy
    redirect_to artists_path
  end

  def update
    artist = Artist.find(params['id'])
    artist.update(artist_params)
    redirect_to artist
  end
  private
  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :image, :period)
  end

end

21/moma_app/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def create
    @work = Work.create(work_params)
    redirect_to works_path
  end

  def new
    @work = Work.new
  end

  def edit
    @work = Work.find(params["id"])
  end

  def show
    @work = Work.find(params["id"])
  end

  def update
    work = Work.find(params['id'])
    work.update(work_params)
    redirect_to work
  end

  def destroy
    work = Work.find(params['id'])
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:year,:medium,:style,:image,:title,:artist_id)
  end
end

21/moma_app/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: 'true' %>
  </p>
  <p>
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </p>
  <p>
    <%= f.label :dob, "Date of birth" %>
    <%= f.text_field :dob, placeholder: 'YYYY-MM-DD' %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </p>

  <%= f.submit %>
<% end %>

21/moma_app/app/views/artists/edit.html.erb
<h2>Updating <%= @artist.name %></h2>
<%= render partial: 'form' %>

21/moma_app/app/views/artists/index.html.erb
<% @artists.each do |artist| %>
  <ul>
    <li><%= image_tag(artist.image, class: 'thumb') %></li>
    <li><%= link_to(artist.name, artist) %></li>
    <li><%= artist.nationality %></li>
    <li><%= artist.dob.strftime('%B %d %Y') if artist.dob %></li>
    <li><%= artist.period %></li>
    <li><%= link_to("Edit", edit_artist_path(artist)) %></li>
    <li><%= link_to("Delete", artist , data: { method: :delete, confirm: "are you sure you want to delete #{artist.name}?"}) %></li>
  </ul>
<% end %>

21/moma_app/app/views/artists/new.html.erb
<h2>New Artist</h2>
<%= render partial: 'form' %>

21/moma_app/app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>
<ul>
  <li><%= image_tag(@artist.image, class: 'medium') %></li>
  <li><%= @artist.nationality %></li>
  <li><%= @artist.dob.strftime('%B %d %Y') %></li>
  <li><%= @artist.period %></li>
</ul>
<% @artist.works.each do |work| %>
  <ul class="works">
    <li><%= link_to(work.title, work) %></li>
    <li><%= image_tag(work.image, class: 'small') %></li>
  </ul>
<% end %>