20/planetr/config/routes.rb
Rails.application.routes.draw do
  get '/planets' => 'planets#index'
  get '/planets/new' => 'planets#new'
  post '/planets' => 'planets#create'
  get '/planets/:id' => 'planets#show', as: 'planet'
  post '/planets/:id/delete' => 'planets#destroy', as: 'planet_delete'
  get '/planets/:id/edit' => 'planets#edit', as: 'planet_edit'
  post '/planets/:id' => 'planets#update'

end

20/planetr/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  orbit      :float
#  mass       :float
#  diameter   :float
#  moons      :integer
#  created_at :datetime
#  updated_at :datetime
#

class Planet < ActiveRecord::Base
end

20/planetr/app/models/seed.rb
Planet.destroy_all

Planet.create({name: 'Earth', orbit: 1, moons: 1})
Planet.create({name: 'Mars', orbit: 1.5, moons: 2})
Planet.create({name: 'Venus', orbit: 0.7, moons: 0})
Planet.create({name: 'Jupiter', orbit: 3.7, moons: 7})
Planet.create({name: 'Neptune', orbit: 8.6, moons: 3})

20/planetr/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def index
    @planets = Planet.all
  end

  def new
  end

  def create
    #render text: 'test test test test'
    #planet = Planet.create params[:planet]
    Planet.create params.require(:planet).permit(:name, :image, :diameter, :mass, :moons)
    redirect_to planets_path
  end

  def show
    id = params["id"]
    @planet = Planet.find(id)
  end

  def destroy
    @planet = Planet.find(params["id"])
    @planet.destroy
    redirect_to planets_path
  end

  def edit
    @planet = Planet.find(params["id"])
  end

  def update
    @planet = Planet.find(params['id'])
    @planet.update params.require(:planet).permit(:name, :image, :diameter, :mass, :moons)
    redirect_to planets_path
  end
end

20/planetr/app/views/planets/edit.html.erb
<form action="<%= planet_path @planet %>" method="post">
  <p>Name<input type="text" name="planet[name]" autofocus value="<%= @planet.name %>"></p>
  <p>Images<input type="url" name="planet[image]" value="<%= @planet.image %>"></p>
  <p>Diameter<input type="text" name="planet[diameter]" value="<%= @planet.diameter %>"></p>
  <p>Mass<input type="text" name='planet[mass]' value="<%= @planet.mass %>"></p>
  <p>Moons<input type="text" name ='planet[moons]' value="<%= @planet.moons %>"></p>
  <button>Submit</button>
</form>

20/planetr/app/views/planets/index.html.erb
<% @planets.each do |planet| %>
  <p>
    <%= link_to(planet.name, planet_path(planet.id)) %> has <%= pluralize(planet.moons, 'moon') %>
    <%= button_to('Delete Planet',planet_delete_path(planet.id)) %>
  </p>
<% end %>

20/planetr/app/views/planets/new.html.erb
<form action="/planets" method="post">
  <p>Name<input type="text" name="planet[name]" autofocus></p>
  <p>Images<input type="url" name="planet[image]"></p>
  <p>Diameter<input type="text" name="planet[diameter]"></p>
  <p>Mass<input type="text" name='planet[mass]'></p>
  <p>Moons<input type="text" name ='planet[moons]'></p>
  <button>Submit</button>
</form>

20/planetr/app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>
<%= image_tag("#{@planet.image}", class: 'thumb') if @planet.image %>
<p>Orbit: <%= @planet.orbit %></p>
<p>Mass: <%= @planet.mass %></p>
<p>Diameter: <%= @planet.diameter %></p>
<p>Moons: <%= @planet.moons %></p>

<p><%= link_to("Edit", planet_edit_path(@planet)) %></p>